"use client";

import { useCallback } from "react";
import { motion } from "framer-motion";
import { Download, Copy, AlertTriangle, ListChecks } from "lucide-react";
import type { AdvisorResult, PillarKey } from "@/types/advisor";
import { PILLAR_KEYS, PILLAR_LABELS } from "@/types/advisor";
import { buildADRMarkdown, adrFileName } from "@/lib/advisor/adr-export";
import PillarCard from "./PillarCard";

interface Props {
  result: AdvisorResult;
}

export default function AdvisorResult({ result }: Props) {
  const handleDownload = useCallback(() => {
    const md = buildADRMarkdown(result);
    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = adrFileName(result);
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }, [result]);

  const handleCopy = useCallback(async () => {
    const md = buildADRMarkdown(result);
    try {
      await navigator.clipboard.writeText(md);
    } catch {
      /* clipboard unavailable; user can use Download */
    }
  }, [result]);

  return (
    <div className="space-y-8">
      <motion.section
        initial={{ opacity: 0, y: 8 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="rounded-2xl border border-brand-200 dark:border-brand-900/50 bg-gradient-to-br from-brand-50 to-white dark:from-brand-950/40 dark:to-slate-900/60 p-6"
      >
        <div className="flex items-center justify-between gap-4 flex-wrap mb-3">
          <h2 className="text-xl font-semibold text-slate-900 dark:text-white">
            Overall WAF Score
          </h2>
          <div className="flex items-center gap-2">
            <span className="text-3xl font-bold text-brand-600 dark:text-brand-400">
              {result.overall.score}
            </span>
            <span className="text-base text-slate-500 dark:text-slate-400">/ 5</span>
          </div>
        </div>
        <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          {result.overall.summary}
        </p>
      </motion.section>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {PILLAR_KEYS.map((key: PillarKey, i) => (
          <PillarCard
            key={key}
            label={PILLAR_LABELS[key]}
            pillar={result.pillars[key]}
            delay={i * 0.05}
          />
        ))}
      </div>

      <section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/60 p-6">
        <h3 className="text-lg font-semibold text-slate-900 dark:text-white flex items-center gap-2 mb-3">
          <AlertTriangle className="w-5 h-5 text-amber-600" aria-hidden="true" />
          Top Risks
        </h3>
        <ul className="space-y-1.5 text-sm text-slate-700 dark:text-slate-300 list-disc pl-5">
          {result.topRisks.map((r, i) => (
            <li key={i}>{r}</li>
          ))}
        </ul>
      </section>

      {result.recommendedAzureServices.length > 0 && (
        <section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/60 p-6">
          <h3 className="text-lg font-semibold text-slate-900 dark:text-white flex items-center gap-2 mb-3">
            <ListChecks className="w-5 h-5 text-brand-600 dark:text-brand-400" aria-hidden="true" />
            Recommended Azure Services
          </h3>
          <div className="flex flex-wrap gap-1.5">
            {result.recommendedAzureServices.map((s, i) => (
              <span
                key={i}
                className="text-sm font-medium px-2.5 py-1 rounded-full bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 border border-slate-200 dark:border-slate-700"
              >
                {s}
              </span>
            ))}
          </div>
        </section>
      )}

      <section className="rounded-2xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-slate-900/60 p-6">
        <div className="flex items-start justify-between gap-4 flex-wrap mb-4">
          <div>
            <h3 className="text-lg font-semibold text-slate-900 dark:text-white">
              Draft ADR — {result.suggestedADR.title}
            </h3>
            <p className="text-xs text-slate-500 dark:text-slate-400 mt-0.5">
              Generated by the advisor. Review before adopting.
            </p>
          </div>
          <div className="flex gap-2">
            <button
              type="button"
              onClick={handleCopy}
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium border border-slate-200 dark:border-slate-700 text-slate-700 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-800 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"
            >
              <Copy className="w-4 h-4" aria-hidden="true" />
              Copy markdown
            </button>
            <button
              type="button"
              onClick={handleDownload}
              className="inline-flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium bg-brand-600 hover:bg-brand-700 text-white focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 focus-visible:ring-offset-2"
            >
              <Download className="w-4 h-4" aria-hidden="true" />
              Download .md
            </button>
          </div>
        </div>

        <dl className="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
          <div>
            <dt className="font-semibold text-slate-900 dark:text-white mb-1">Context</dt>
            <dd className="text-slate-700 dark:text-slate-300 whitespace-pre-line">{result.suggestedADR.context}</dd>
          </div>
          <div>
            <dt className="font-semibold text-slate-900 dark:text-white mb-1">Decision</dt>
            <dd className="text-slate-700 dark:text-slate-300 whitespace-pre-line">{result.suggestedADR.decision}</dd>
          </div>
          <div>
            <dt className="font-semibold text-slate-900 dark:text-white mb-1">Rationale</dt>
            <dd className="text-slate-700 dark:text-slate-300 whitespace-pre-line">{result.suggestedADR.rationale}</dd>
          </div>
          <div>
            <dt className="font-semibold text-slate-900 dark:text-white mb-1">Trade-offs</dt>
            <dd className="text-slate-700 dark:text-slate-300 whitespace-pre-line">{result.suggestedADR.tradeoffs}</dd>
          </div>
          <div className="md:col-span-2">
            <dt className="font-semibold text-slate-900 dark:text-white mb-1">Expected outcome</dt>
            <dd className="text-slate-700 dark:text-slate-300 whitespace-pre-line">{result.suggestedADR.outcome}</dd>
          </div>
        </dl>
      </section>
    </div>
  );
}
